fields:
  site_ownership:
    display: Site Ownership
    type: section
  google_site_verification:
    instructions: For the `<meta name='google-site-verification'>` tag. Only enter the code in the `content=''`, not the entire tag. [Here's how to get it](https://www.google.com/webmasters/verification/).
    type: text
  bing_site_verification:
    instructions: For the `<meta name='msvalidate.01'>` tag. Only enter the code in the `content=''`, not the entire tag. [Here's how to get it](https://www.bing.com/webmaster/help/how-to-verify-ownership-of-your-site-afcfefc6).
    type: text
  google_tag_manager_id:
    display: Google Tag Manager ID
    instructions: If you enter your Google Tag Manager ID here, the Google Tag Manager script tags will be included in your `<head>`. Only enter the ID, e.g. `GTM-XXXXXX`, not the entire script code. [Here's how to get it](https://support.google.com/tagmanager/answer/6102821?hl=en).
    type: text
  google_analytics_tracking_id:
    display: Google Analytics Tracking ID
    instructions: If you enter your Google Analytics Tracking ID here, the Google Analytics script tags will be included in your `<head>`. Only enter the ID, e.g. `UA-XXXXXX-XX`, not the entire script code. [Here's how to get it](https://support.google.com/analytics/answer/1032385?hl=en).
    type: text
  automatically_send_pageview:
    display: Automatically send Google Analytics PageView
    instructions: Controls whether the Google Analytics script automatically sends a PageView to Google Analytics when your pages are loaded
    type: toggle
    default: true
  google_analytics_ip_anonymization:
    display: Google Analytics IP Anonymization
    instructions: When a customer of Analytics requests IP address anonymization, Analytics anonymizes the address as soon as technically feasible at the earliest possible stage of the collection network
    type: toggle
    default: true
  google_analytics_plugins:
    display: Google Analytics Plugins
    instructions: Select which Google Analytics plugins to enable. [Learn More](https://developers.google.com/analytics/devguides/collection/analyticsjs/)
    type: checkboxes
    options:
      googleAnalyticsAdvertising: Display Features
      googleAnalyticsEcommerce: Ecommerce
      googleAnalyticsEEcommerce: Enhanced Ecommerce
      googleAnalyticsLinkAttribution: Enhanced Link Attribution
      googleAnalyticsLinker: Linker
  site_owner_entity_type:
    display: Site Owner Entity Type
    instructions: The type of entity that owns this website. Choose as general or specific of an Entity Type as you wish. Leave a sub-type blank if you don't want to specify a sub-type.
    type: select
    options:
      organization: Organization
      person: Person
  general_info:
    display: General Info
    type: section
  entity_name:
    instructions: The name of the entity that owns the website
    type: text
  alternate_entity_name:
    instructions: An alternate or nickname for the entity that owns the website
    type: text
  entity_description:
    instructions: A description of the entity that owns the website
    type: textarea
    rows: 2
  entity_url:
    display: Entity URL
    instructions: A URL for the entity that owns the website
    type: text
    validate: url
  entity_brand:
    instructions: An image or logo that represents the entity that owns the website. The image must be in JPG, PNG, or GIF format.
    type: assets
    max_files: 1
    container: images
  entity_telephone:
    instructions: The primary contact telephone number for the entity that owns the website
    type: text
  entity_email:
    instructions: The primary contact email address for the entity that owns the website
    type: text
    validate: email
  location_info:
    type: section
  entity_street_address:
    instructions: The street address of the entity that owns the website, e.g. 123 Main Street
    type: text
  entity_locality:
    instructions: The locality of the entity that owns the website, e.g. Portchester
    type: text
    width: 50
  entity_region:
    instructions: The region of the entity that owns the website, e.g. New York or NY
    type: text
    width: 50
  entity_postal_code:
    instructions: The postal code of the entity that owns the website, e.g. 14580
    type: text
    width: 50
  entity_country:
    instructions: The country in which the entity that owns the website is located, e.g. US
    type: text
    width: 50
  entity_latitude:
    instructions: The latitude of the location of the entity that owns the website, e.g. -120.5436367
    type: text
    width: 50
  entity_longitude:
    instructions: The longitude of the location of the entity that owns the website, e.g. 80.6033588
    type: text
    width: 50
